openapi: 3.0.3
info:
  title: webservice
  version: v1.0.0
components: 
  schemas:
    image:
      type: string
      title: Image Name
      description: Docker image name
      x-ui:
        group: Basic
    ports:
      title: Ports
      type: array
      description: Service ports to expose
      default:
      - 80
      items:
        type: integer
      x-ui:
        group: Basic
    env:
      title: Environment Variables
      type: object
      description: Name and value pairs to set as the environment variables
      additionalProperties:
        type: string
      x-ui:
        group: Basic
    replicas:
      title: Replicas
      type: number
      description: Replicas to deploy
      default: 1
      x-ui:
        group: Basic
    request_cpu:
      title: CPU Request
      type: string
      description: CPU request. e.g. 0.5, 1, 2
      default: '0.1'
      x-ui:
        group: Resources
    request_memory:
      title: Memory Request
      type: string
      default: 128Mi
      description: Memory request. e.g. 128Mi, 512Mi, 1Gi, 2Gi, 4Gi
      x-ui:
        widget: MemoryInput
        group: Resources
    limit_cpu:
      title: CPU Request
      type: string
      description: CPU limit. e.g. 0.5, 1, 2
      default: ''
      x-ui:
        group: Resources
    limit_memory:
      title: Memory Request
      type: string
      description: Memory limit. e.g. 128Mi, 512Mi, 1Gi, 2Gi, 4Gi
      default: ''
      x-ui:
        widget: MemoryInput
        group: Resources
    namespace:
      title: Namespace
      type: string
      description: Namespace to deploy. Auto-generated if empty.
      default: ''
      x-ui:
        widget: NamespaceSelect
        group: Advance
    name:
      title: Deployment Name
      type: string
      description: Name of the deployment resource. Auto-generated if empty.
      default: ''
      x-ui:
        group: Advance
